name: valuta_kurslari
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  talker_dio_logger: ^4.3.2
  circular_reveal_animation: ^2.0.1
  flutter_toggle_tab: ^1.4.1
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  easy_localization: ^3.0.3
  google_mobile_ads: ^4.0.0
  package_info_plus: ^5.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: MyID
      fonts:
        - asset: assets/fonts/myid_bold.ttf
          weight: 700
    - family: PaynetM
      fonts:
        - asset: assets/fonts/pnfont_medium.ttf
          weight: 700
    - family: PaynetB
      fonts:
        - asset: assets/fonts/pnfont_semibold.ttf
          weight: 700
    - family: Noir
      fonts:
        - asset: assets/fonts/noir_std.ttf
          weight: 700
    - family: PFair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-VariableFont_wght.ttf
          weight: 700

